spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/harudb?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all